/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemadelmotel;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Registrarse extends javax.swing.JFrame {
    int ojo=0;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registrarse.class.getName());

    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        registraseahora = new javax.swing.JButton();
        backtoiniciosesion = new javax.swing.JButton();
        Registronombre = new javax.swing.JTextField();
        Registroemail = new javax.swing.JTextField();
        registrorespuestaseg = new javax.swing.JTextField();
        Registroseguridad = new javax.swing.JComboBox<>();
        ojo2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        registrocontra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Registrarse");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Email");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Pregunta de seguridad");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Respuesta");

        registraseahora.setText("Registrarse ahora");
        registraseahora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registraseahoraActionPerformed(evt);
            }
        });

        backtoiniciosesion.setText("Volver al inicio de sesión");
        backtoiniciosesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoiniciosesionActionPerformed(evt);
            }
        });

        Registronombre.setText("jTextField1");

        Registroemail.setText("jTextField2");

        registrorespuestaseg.setText("jTextField4");

        Registroseguridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "¿Cuál es el apellido de tu primera profesora de kinder?", "¿En qué calle vivías cuando tenías 10 años?", "¿Cuál era tu color favorito cuando tenias 13 años?", "¿Qué apodo te ponían en la escuela?", "¿En qué año empezaste la universidad o tu primer empleo?", "¿Cuál es tu canción favorita?" }));

        ojo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/closed-eye44.png"))); // NOI18N
        ojo2.setText("jLabel6");
        ojo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ojo2MouseClicked(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x-icon-150997 (2).png"))); // NOI18N
        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        registrocontra.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(106, 106, 106)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Registroemail)
                                    .addComponent(Registronombre)
                                    .addComponent(registrocontra)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(33, 33, 33)
                                .addComponent(Registroseguridad, 0, 1, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(registraseahora)
                                        .addGap(43, 43, 43)
                                        .addComponent(backtoiniciosesion))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(112, 112, 112)
                                        .addComponent(registrorespuestaseg, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ojo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Registronombre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Registroemail, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(registrocontra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registroseguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(ojo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(registrorespuestaseg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registraseahora)
                    .addComponent(backtoiniciosesion))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registraseahoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registraseahoraActionPerformed
if(Registronombre.getText().equals("")){
    JOptionPane.showMessageDialog(this, "todos los campos deben completarse");
    Registronombre.requestFocus();
}
else if(Registroemail.getText().equals("")){
    JOptionPane.showMessageDialog(this, "todos los campos deben completarse");
    Registroemail.requestFocus();
}
else if(registrocontra.getText().equals("")){
    JOptionPane.showMessageDialog(this, "todos los campos deben completarse");
    registrocontra.requestFocus();
}
else if(registrorespuestaseg.getText().equals("")){
    JOptionPane.showMessageDialog(this, "todos los campos deben completarse");
    registrorespuestaseg.requestFocus();
}
else{
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","Romero10251530$");
        pst=con.prepareStatement("select * from usuario where Email=?");
        pst.setString(1,Registroemail.getText());
        rs=pst.executeQuery();
        if(rs.next()){
        JOptionPane.showMessageDialog(this, "Use otro Email no registrado");
        }
        else{
            pst=con.prepareStatement("insert into usuario(Usuario_nombre,Email,Contrasena,Pregunta,Respuesta)values(?,?,?,?,?)");
            pst.setString(1, Registronombre.getText());
            pst.setString(2, Registroemail.getText());
            pst.setString(3, registrocontra.getText());
            pst.setString(4, Registroseguridad.getItemAt(Registroseguridad.getSelectedIndex()));
            pst.setString(5, registrorespuestaseg.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Registro completado con éxito\n inicie sesion ahora");
         
        }
        
    } catch (ClassNotFoundException ex) {
        System.getLogger(Registrarse.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
    } catch (SQLException ex) {
        System.getLogger(Registrarse.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
    }
       
}
    }//GEN-LAST:event_registraseahoraActionPerformed

    private void backtoiniciosesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoiniciosesionActionPerformed
    new login().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_backtoiniciosesionActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int yes=JOptionPane.showConfirmDialog(this,"Está Seguro?","Salir",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
if(yes==JOptionPane.YES_OPTION)
        System.exit(0);        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ojo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojo2MouseClicked
 if (ojo == 0) {
    ojo2.setIcon(new ImageIcon("C:\\Users\\Usuario\\OneDrive\\Escritorio\\Motel\\systemadelmotel\\src\\imagenes\\closed-eye44.png"));
    ojo = 1;
    registrocontra.setEchoChar('*');
} 
else {
    ojo2.setIcon(new ImageIcon("C:\\Users\\Usuario\\OneDrive\\Escritorio\\Motel\\systemadelmotel\\src\\imagenes\\open-eye2.png"));
    ojo = 0; 
    registrocontra.setEchoChar((char)0);
}        // TODO add your handling code here:
    }//GEN-LAST:event_ojo2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registrarse().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Registroemail;
    private javax.swing.JTextField Registronombre;
    private javax.swing.JComboBox<String> Registroseguridad;
    private javax.swing.JButton backtoiniciosesion;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel ojo2;
    private javax.swing.JButton registraseahora;
    private javax.swing.JPasswordField registrocontra;
    private javax.swing.JTextField registrorespuestaseg;
    // End of variables declaration//GEN-END:variables
}
