/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemadelmotel;
  
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import systemadelmotel.ValidadorCliente;
import systemadelmotel.Edad;
import com.github.lgooddatepicker.components.DatePicker;
import com.github.lgooddatepicker.components.DatePickerSettings;
import com.github.lgooddatepicker.optionalusertools.DateVetoPolicy;
import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JCheckBox;
import javax.swing.JTextField;
import systemadelmotel.Menu;





/**
 *
 * @author Usuario
 */
public class Reserva extends javax.swing.JFrame {
    Connection con=null;
    Statement st=null;
    java.sql.PreparedStatement pst=null;
    ResultSet rs=null;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Reserva.class.getName());
    
    private boolean datosConfirmados = false;

    


    /**
     * Creates new form Reserva
     */
    ServiciosExtraPanel serviciosPanel;

    
    public Reserva() {
        initComponents();
        
        serviciosPanel = new ServiciosExtraPanel();
jPanel5.add(serviciosPanel);

  // LÓGICA DE SELECCIÓN DE SERVICIOS EXTRAS
javax.swing.JCheckBox[] servicios = {
    checkSpa, checkGimnasio, checkJuegos, checkYoga
};

// Acción para los servicios extra (no "Ninguno")
for (JCheckBox check : servicios) {
    check.addActionListener(e -> {
        // Si se selecciona algún servicio, desactiva "Ninguno"
        if (check.isSelected()) {
            checkNinguno.setSelected(false);
        }

        // Si "Ninguno" está activado, se desactiva y se habilitan los demás
        if (!checkNinguno.isSelected()) {
            for (JCheckBox c : servicios) {
                c.setEnabled(true);
            }
        }
    });
}

// Acción para "Ninguno"
checkNinguno.addActionListener(e -> {
    boolean ningunoSeleccionado = checkNinguno.isSelected();

    for (JCheckBox c : servicios) {
        c.setSelected(false);
        c.setEnabled(!ningunoSeleccionado); // deshabilita si "Ninguno" está activado
    }
});

    
        
        generocombo.setSelectedIndex(-1);
       
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","Romero10251530$");
        } catch (ClassNotFoundException | SQLException ex) {
            System.getLogger(Habitaciones.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Nombre1 = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        Email1 = new javax.swing.JTextField();
        Direccion1 = new javax.swing.JTextField();
        Nacionalidad1 = new javax.swing.JTextField();
        Identificacion1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        generocombo = new javax.swing.JComboBox<>();
        Fechanacimiento = new com.github.lgooddatepicker.components.DatePicker();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        econom = new javax.swing.JRadioButton();
        supero = new javax.swing.JRadioButton();
        Suite = new javax.swing.JRadioButton();
        indv = new javax.swing.JRadioButton();
        dobl = new javax.swing.JRadioButton();
        tri = new javax.swing.JRadioButton();
        checkSpa = new javax.swing.JCheckBox();
        checkGimnasio = new javax.swing.JCheckBox();
        checkJuegos = new javax.swing.JCheckBox();
        checkYoga = new javax.swing.JCheckBox();
        checkNinguno = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        nombreprop = new javax.swing.JTextField();
        numerot = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cvcact = new javax.swing.JTextField();
        fechaexp = new com.github.lgooddatepicker.components.DatePicker();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        confirmar = new javax.swing.JButton();
        fechin = new com.github.lgooddatepicker.components.DatePicker();
        fechasa = new com.github.lgooddatepicker.components.DatePicker();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Datos Personales");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Telefono");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Dirección");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Nacionalidad");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Identifiación");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Fecha de nacimiento");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Genero");

        generocombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(Email1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(Nacionalidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Direccion1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(Identificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(79, 79, 79)
                                .addComponent(generocombo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Fechanacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(90, 90, 90)
                                .addComponent(Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(312, 312, 312))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Fechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(generocombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Identificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Email1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Nacionalidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        jLabel7.getAccessibleContext().setAccessibleName("Cedula \n    o \nPasaporte");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Informacion de la habitacion");

        jLabel11.setText("Tipo de Habitaicon");

        jLabel12.setText("Capacidad");

        jLabel13.setText("servicios extras");

        buttonGroup1.add(econom);
        econom.setText("Economica");

        buttonGroup1.add(supero);
        supero.setText("Superior");

        buttonGroup1.add(Suite);
        Suite.setText("Suite");

        buttonGroup2.add(indv);
        indv.setText("Individual");

        buttonGroup2.add(dobl);
        dobl.setText("Doble");

        buttonGroup2.add(tri);
        tri.setText("Triple");

        checkSpa.setText("Spa");

        checkGimnasio.setText("Gimnasio");

        checkJuegos.setText("Zona de Juegos");

        checkYoga.setText("Salón de Yoga");

        checkNinguno.setText("Ninguno");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dobl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)))
                            .addComponent(econom, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkSpa)
                                    .addComponent(checkGimnasio))))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(indv, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(supero, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                .addComponent(tri, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkYoga)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(checkJuegos)
                                        .addGap(50, 50, 50)
                                        .addComponent(checkNinguno)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Suite, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addGap(41, 41, 41)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(econom)
                    .addComponent(supero)
                    .addComponent(Suite))
                .addGap(42, 42, 42)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobl)
                    .addComponent(indv)
                    .addComponent(tri))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkSpa)
                    .addComponent(checkJuegos)
                    .addComponent(checkNinguno))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkGimnasio)
                    .addComponent(checkYoga))
                .addGap(60, 60, 60))
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("Pago");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Numero de targeta");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("CVC CODE");

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Nombre del propietario");

        nombreprop.setText("jTextField1");

        numerot.setText("jTextField2");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Fecha de expiración");

        cvcact.setText("jTextField3");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreprop, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(numerot))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fechaexp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(77, 77, 77)
                                .addComponent(cvcact, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(nombreprop, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(fechaexp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(numerot, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cvcact, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setText("Estadia");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel14.setText("Fecha de ingreso");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel15.setText("Fecha de salida");

        confirmar.setText("confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechasa, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(fechin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addGap(108, 108, 108))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(confirmar)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(126, 126, 126))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel17)
                .addGap(26, 26, 26)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fechin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addComponent(jLabel15)
                .addGap(29, 29, 29)
                .addComponent(fechasa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(confirmar)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo-mejorado-removebg-preview (1).png"))); // NOI18N
        jButton2.setText("jButton2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (!datosConfirmados) {
    JOptionPane.showMessageDialog(this, "Primero debes confirmar los datos antes de guardar.");
    return;
}
         if (numerot.getText().trim().isEmpty()) {
    numerot.requestFocus();
    JOptionPane.showMessageDialog(this, "Debe ingresar el número de tarjeta.");
    return;
} else if (numerot.getText().length() != 16 || !numerot.getText().matches("\\d+")) {
    numerot.requestFocus();
    JOptionPane.showMessageDialog(this, "El número de tarjeta debe tener 16 dígitos numéricos.");
    return;
}

if (fechaexp.getDate() == null) {
    JOptionPane.showMessageDialog(this, "Debe ingresar la fecha de expiración.");
    fechaexp.requestFocus();
    return;
}

// Validar que no sea una fecha en el pasado
LocalDate fechaSeleccionada = fechaexp.getDate();
LocalDate hoy = LocalDate.now();
if (fechaSeleccionada.isBefore(hoy)) {
    JOptionPane.showMessageDialog(this, "La fecha de expiración ya ha pasado.");
    fechaexp.requestFocus();
    return;
}

if (cvcact.getText().trim().isEmpty()) {
    cvcact.requestFocus();
    JOptionPane.showMessageDialog(this, "Debe ingresar el código CVC.");
    return;
} else if (cvcact.getText().length() != 3 || !cvcact.getText().matches("\\d+")) {
    cvcact.requestFocus();
    JOptionPane.showMessageDialog(this, "El código CVC debe tener 3 dígitos numéricos.");
    return;
}
    
    try {
    // Obtener tipo habitación
    String tipoHabitacion = "";
    if (econom.isSelected()) tipoHabitacion = econom.getText();
    else if (supero.isSelected()) tipoHabitacion = supero.getText();
    else if (Suite.isSelected()) tipoHabitacion = Suite.getText();

    // Capacidad
    int capacidad = 0;
    if (indv.isSelected()) capacidad = 1;
    else if (dobl.isSelected()) capacidad = 2;
    else if (tri.isSelected()) capacidad = 3;

    // Fechas
    java.sql.Date sqlFechaIngreso = java.sql.Date.valueOf(fechin.getDate());
    java.sql.Date sqlFechaSalida = java.sql.Date.valueOf(fechasa.getDate());
    java.sql.Date sqlFechanacimiento = java.sql.Date.valueOf(Fechanacimiento.getDate());

    // Buscar habitación disponible
    String buscar = "SELECT * FROM habitacion WHERE tipoHabitacion=? AND capacidad_H=? AND (Disponibilidad IS NULL OR Disponibilidad='Disponible') LIMIT 1";
    pst = con.prepareStatement(buscar);
    pst.setString(1, tipoHabitacion);
    pst.setInt(2, capacidad);
    rs = pst.executeQuery();

    if (rs.next()) {
        int idHabAsignada = rs.getInt("idHabitacion");

        // Actualizar la habitación como ocupada
        String actualizar = "UPDATE habitacion SET Disponibilidad='Ocupada', `Check_in-fecha`=?, `check_out-fecha`=? WHERE idHabitacion=?";
        pst = con.prepareStatement(actualizar);
        pst.setDate(1, sqlFechaIngreso);
        pst.setDate(2, sqlFechaSalida);
        pst.setInt(3, idHabAsignada);
        pst.executeUpdate();

        // Ahora insertar en cliente1 incluyendo el idHabitacion
        pst = con.prepareStatement("insert into cliente1(Identificacion,Nombre,Numero_phone,Email,Nacionalidad,Fecha_nacimiento,Genero,direccion,Habitacion_cliente, Capacidad_h, Servicios_extras, Fecha_ingreso, Fecha_lastday, clientetargeta, 3digitsback,idHabitacion)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

        pst.setString(1, Identificacion1.getText());
        pst.setString(2, Nombre1.getText());
        pst.setString(3, Telefono.getText());
        pst.setString(4, Email1.getText());
        pst.setString(5, Nacionalidad1.getText());
        pst.setDate(6, sqlFechanacimiento);
        pst.setString(7, generocombo.getSelectedItem().toString());
        pst.setString(8, Direccion1.getText());
        pst.setString(9, tipoHabitacion);
        pst.setString(10, String.valueOf(capacidad));

        StringBuilder serviciosExtras = new StringBuilder();

if (checkSpa.isSelected()) {
    serviciosExtras.append("Spa, ");
}
if (checkGimnasio.isSelected()) {
    serviciosExtras.append("Gimnasio, ");
}
if (checkJuegos.isSelected()) {
    serviciosExtras.append("Zona de Juegos, ");
}
if (checkYoga.isSelected()) {
    serviciosExtras.append("Salón de Yoga, ");
}
if (checkNinguno.isSelected()) {
    serviciosExtras.append("Ninguno");
}

// Elimina la coma final si no se eligió "Ninguno"
String serviciosFinales = serviciosExtras.toString();
if (serviciosFinales.endsWith(", ")) {
    serviciosFinales = serviciosFinales.substring(0, serviciosFinales.length() - 2);
}

// Ahora puedes guardar `serviciosFinales` en la base de datos
pst.setString(11, serviciosFinales); // reemplaza `posicionDelCampo` con el número correspondiente


        pst.setDate(12, sqlFechaIngreso);
        pst.setDate(13, sqlFechaSalida);
        pst.setString(14, numerot.getText());
        pst.setString(15, cvcact.getText());
        pst.setInt(16, idHabAsignada);

        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Reserva completada y habitación asignada.");
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "No hay habitaciones disponibles con esas características. Intente con otra opción.");
    }
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage());
}
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    new Menu().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
 // Validaciones
   if (Identificacion1.getText().equals("")) {
    Identificacion1.requestFocus();
    JOptionPane.showMessageDialog(this, "Llena todos los campos");
    return;
} else if (Nombre1.getText().equals("")) {
    Nombre1.requestFocus();
    JOptionPane.showMessageDialog(this, "Llena todos los campos");
    return;
} else if (Telefono.getText().equals("")) {
    Telefono.requestFocus();
    JOptionPane.showMessageDialog(this, "Llena todos los campos");
    return;
} else if (Email1.getText().equals("")) {
    Email1.requestFocus();
    JOptionPane.showMessageDialog(this, "Llena todos los campos");
    return;
} else if (Nacionalidad1.getText().equals("")) {
    Nacionalidad1.requestFocus();
    JOptionPane.showMessageDialog(this, "Llena todos los campos");
    return;
} else if (Fechanacimiento.getDate() == null) {
    Fechanacimiento.requestFocus();
    JOptionPane.showMessageDialog(this, "Llena todos los campos");
    return;
} else if (generocombo.getSelectedIndex() == -1) {
    generocombo.requestFocus();
    JOptionPane.showMessageDialog(this, "Selecciona un género");
    return;
} else if (Direccion1.getText().equals("")) {
    Direccion1.requestFocus();
    JOptionPane.showMessageDialog(this, "Llena todos los campos");
    return;
} else if (buttonGroup1.getSelection() == null) {
    JOptionPane.showMessageDialog(this, "Selecciona un tipo de habitación");
    return;
} else if (buttonGroup2.getSelection() == null) {
    JOptionPane.showMessageDialog(this, "Elija la capacidad de la Habitación");
    return;
} else if (!checkSpa.isSelected() && !checkGimnasio.isSelected() && !checkJuegos.isSelected() && !checkYoga.isSelected() && !checkNinguno.isSelected()) {
    JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un servicio extra.");
    return;
} else if (fechin.getDate() == null) {
    fechin.requestFocus();
    JOptionPane.showMessageDialog(this, "Seleccione la fecha de entrada");
    return;
} else if (fechasa.getDate() == null) {
    fechasa.requestFocus();
    JOptionPane.showMessageDialog(this, "Seleccione la fecha de salida");
    return;
} else if (numerot.getText().equals("")) {
    numerot.requestFocus();
    JOptionPane.showMessageDialog(this, "Ingrese el número de tarjeta");
    return;
} else if (cvcact.getText().equals("")) {
    cvcact.requestFocus();
    JOptionPane.showMessageDialog(this, "Ingrese el CVC");
    }
    else {
        
    LocalDate fechaNacimiento = Fechanacimiento.getDate();
if (!Edad.esMayorDeEdad(fechaNacimiento)) {
    JOptionPane.showMessageDialog(this, "No se permiten registros de menores de edad. Debe tener al menos 18 años.");
    return;
}
      
    
    
    String cedulaIngresada = Identificacion1.getText();
    if (ValidadorCliente.identificacionExiste(cedulaIngresada)) {
    JOptionPane.showMessageDialog(this, "Ya existe una persona registrada con esa identificación.");
    return;
}

}
double precioServicio = serviciosPanel.getPrecioServicios();
String servicioExtra = serviciosPanel.getServiciosSeleccionados();

 if (buttonGroup1.getSelection() == null ||
    buttonGroup2.getSelection() == null ||
    fechin.getDate() == null || fechasa.getDate() == null) {
    JOptionPane.showMessageDialog(this, "Debes completar todos los campos antes de confirmar.");
    return;
}

// Obtener datos seleccionados
String tipoHabitacion = econom.isSelected() ? "Economica"
                     : supero.isSelected() ? "Superior"
                     : "Suite";

int capacidad = indv.isSelected() ? 1 : dobl.isSelected() ? 2 : 3;

StringBuilder servicios = new StringBuilder();

if (checkSpa.isSelected()) servicios.append("Spa, ");
if (checkGimnasio.isSelected()) servicios.append("Gimnasio, ");
if (checkJuegos.isSelected()) servicios.append("Zona de Juegos, ");
if (checkYoga.isSelected()) servicios.append("Salón de Yoga, ");
if (checkNinguno.isSelected()) servicios.append("Ninguno");

String servicioextra = servicios.toString();
if (servicioextra.endsWith(", ")) {
    servicioextra = servicioextra.substring(0, servicioextra.length() - 2);
}

java.time.LocalDate checkIn = fechin.getDate();
java.time.LocalDate checkOut = fechasa.getDate();
long noches = java.time.temporal.ChronoUnit.DAYS.between(checkIn, checkOut);

double precioNoche = 0;
if (tipoHabitacion.equals("Economica")) {
    precioNoche = (capacidad == 1) ? 25 : (capacidad == 2) ? 30 : 35;
} else if (tipoHabitacion.equals("Superior")) {
    precioNoche = (capacidad == 1) ? 35 : (capacidad == 2) ? 40 : 45;
} else if (tipoHabitacion.equals("Suite")) {
    precioNoche = (capacidad == 1) ? 50 : (capacidad == 2) ? 60 : 70;
}

double total = (precioNoche * noches) + precioServicio;

// Verificar disponibilidad en la base de datos
try {
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb", "root", "Romero10251530$");

    String sql = "SELECT idHabitacion FROM habitacion WHERE tipoHabitacion = ? AND capacidad_H = ? AND (Disponibilidad IS NULL OR Disponibilidad != 'Ocupada') LIMIT 1";
    PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1, tipoHabitacion);
    pst.setInt(2, capacidad);
    ResultSet rs = pst.executeQuery();

    if (rs.next()) {
        // Hay al menos una habitación disponible

        // Crear resumen de factura
        String resumen =
            "----- FACTURA DE RESERVA -----\n\n" +
            "Habitación: " + tipoHabitacion + "\n" +
            "Capacidad: " + capacidad + " persona(s)\n" +
            "Check-in: " + checkIn + "\n" +
            "Check-out: " + checkOut + "\n" +
            "Noches: " + noches + "\n" +
            "Precio por noche: B/. " + String.format("%.2f", precioNoche) + "\n" +
            "Servicio extra: " + servicioextra + " (B/. " + String.format("%.2f", precioServicio) + ")\n" +
            "-----------------------------\n" +
            "TOTAL: B/. " + String.format("%.2f", total) + "\n";

        int opcion = JOptionPane.showConfirmDialog(
            this,
            resumen,
            "Confirmar Reserva",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.INFORMATION_MESSAGE
        );

        if (opcion == JOptionPane.OK_OPTION) {
            
                datosConfirmados = true;
    JOptionPane.showMessageDialog(this, "Datos confirmados correctamente. Ahora puede continuar con la reserva.");

            
            // Aquí puedes hacer update para marcar como ocupada si deseas
        } else {
            // Cancelado: limpiar todo
            Nombre1.setText("");
            Email1.setText("");
            Direccion1.setText("");
            Identificacion1.setText("");
            Nacionalidad1.setText("");
            Telefono.setText("");
            generocombo.setSelectedIndex(-1);
            buttonGroup1.clearSelection();
            buttonGroup2.clearSelection();
            buttonGroup3.clearSelection();
            Fechanacimiento.setDate(null);
            fechin.setDate(null);
            fechasa.setDate(null);
            JOptionPane.showMessageDialog(this, "Reserva cancelada y datos borrados.");
            this.dispose();
            new Menu().setVisible(true);
        }

    } else {
        // No hay habitación disponible
        JOptionPane.showMessageDialog(this, "No hay habitaciones disponibles con esas características. Por favor elija otra.");
    }

    con.close();
} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error al verificar disponibilidad.");
}
    }//GEN-LAST:event_confirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Reserva().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Direccion1;
    private javax.swing.JTextField Email1;
    private com.github.lgooddatepicker.components.DatePicker Fechanacimiento;
    private javax.swing.JTextField Identificacion1;
    private javax.swing.JTextField Nacionalidad1;
    private javax.swing.JTextField Nombre1;
    private javax.swing.JRadioButton Suite;
    private javax.swing.JTextField Telefono;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox checkGimnasio;
    private javax.swing.JCheckBox checkJuegos;
    private javax.swing.JCheckBox checkNinguno;
    private javax.swing.JCheckBox checkSpa;
    private javax.swing.JCheckBox checkYoga;
    private javax.swing.JButton confirmar;
    private javax.swing.JTextField cvcact;
    private javax.swing.JRadioButton dobl;
    private javax.swing.JRadioButton econom;
    private com.github.lgooddatepicker.components.DatePicker fechaexp;
    private com.github.lgooddatepicker.components.DatePicker fechasa;
    private com.github.lgooddatepicker.components.DatePicker fechin;
    private javax.swing.JComboBox<String> generocombo;
    private javax.swing.JRadioButton indv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField nombreprop;
    private javax.swing.JTextField numerot;
    private javax.swing.JRadioButton supero;
    private javax.swing.JRadioButton tri;
    // End of variables declaration//GEN-END:variables
}
